apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufeisf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ufeisf
  template:
    metadata:
      labels:
        app: ufeisf
    spec:
      containers:
      - image: okteto.dev/ufeisf:latest
        name: ufeisf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "21b907f3-398c-4399-84a1-fdf81db87d29"
        - name: Vless_Path
          value: "/vlhtt555"
        - name: Vmess_UUID
          value: "21b907f3-398c-4399-84a1-fdf81db87d29"
        - name: Vmess_Path
          value: "/vm666tyt"
        - name: Share_Path
          value: "/v2link"
